apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  selector:
    app: regapp

    
  ports:
   - port: 8080   # service port
     targetPort: 8080  # container port

  type: LoadBalancer   
